/**
 * Automation Platform Event Constants
 * Standardized event types for cross-module decoupled communication.
 */
export const EVENT_TYPES = {
  JOB_CREATED: "JOB_CREATED",
  JOB_PUBLISHED: "JOB_PUBLISHED",
  JOB_ARCHIVED: "JOB_ARCHIVED",
  JOB_DELETED: "JOB_DELETED",
  JOB_EXPIRED: "JOB_EXPIRED",
  APPLICATION_CREATED: "APPLICATION_CREATED",
  APPLICATION_STATUS_CHANGED: "APPLICATION_STATUS_CHANGED",
  RESUME_UPLOADED: "RESUME_UPLOADED",
  INTERVIEW_SCHEDULED: "INTERVIEW_SCHEDULED",
  INTERVIEW_RESCHEDULED: "INTERVIEW_RESCHEDULED",
  INTERVIEW_CANCELLED: "INTERVIEW_CANCELLED",
  USER_REGISTERED: "USER_REGISTERED",
};

export const AUTOMATION_JOB_TYPES = {
  ANALYZE_JOB: "ANALYZE_JOB",
  PROCESS_RESUME: "PROCESS_RESUME",
  SCREEN_APPLICATION: "SCREEN_APPLICATION",
  MATCH_CANDIDATES_FOR_JOB: "MATCH_CANDIDATES_FOR_JOB",
  SEND_STATUS_EMAIL: "SEND_STATUS_EMAIL",
  SEND_INTERVIEW_REMINDER: "SEND_INTERVIEW_REMINDER",
  DISPATCH_DAILY_DIGEST: "DISPATCH_DAILY_DIGEST",
  CHECK_EXPIRED_JOBS: "CHECK_EXPIRED_JOBS",
};
